import uuid

from sqlalchemy import Column, Float, Integer, String
from sqlalchemy.dialects.postgresql import UUID

from core.db import Base


class Data(Base):
    id = Column(Integer, primary_key=True, index=True)
    dbn = Column(String)
    school_name = Column(String)
    category = Column(String)
    year = Column(String)
    total_enrollment = Column(Integer, nullable=True)
    grade_k = Column(Integer, nullable=True)
    grade_1 = Column(Integer, nullable=True)
    grade_2 = Column(Integer, nullable=True)
    grade_3 = Column(Integer, nullable=True)
    grade_4 = Column(Integer, nullable=True)
    grade_5 = Column(Integer, nullable=True)
    grade_6 = Column(Integer, nullable=True)
    grade_7 = Column(Integer, nullable=True)
    grade_8 = Column(Integer, nullable=True)
    female_1 = Column(Integer, nullable=True)
    female_2 = Column(Float, nullable=True)
    male_1 = Column(Integer, nullable=True)
    male_2 = Column(Float, nullable=True)
    asian_1 = Column(Integer, nullable=True)
    asian_2 = Column(Float, nullable=True)
    black_1 = Column(Integer, nullable=True)
    black_2 = Column(Float, nullable=True)
    hispanic_1 = Column(Integer, nullable=True)
    hispanic_2 = Column(Float, nullable=True)
    other_1 = Column(Integer, nullable=True)
    other_2 = Column(Float, nullable=True)
    white_1 = Column(Integer, nullable=True)
    white_2 = Column(Float, nullable=True)
    ell_spanish_1 = Column(Integer, nullable=True)
    ell_spanish_2 = Column(Float, nullable=True)
    ell_chinese_1 = Column(Integer, nullable=True)
    ell_chinese_2 = Column(Float, nullable=True)
    ell_bengali_1 = Column(Integer, nullable=True)
    ell_bengali_2 = Column(Float, nullable=True)
    ell_arabic_1 = Column(Integer, nullable=True)
    ell_arabic_2 = Column(Float, nullable=True)
    ell_haitian_creole_1 = Column(Integer, nullable=True)
    ell_haitian_creole_2 = Column(Float, nullable=True)
    ell_french_1 = Column(Integer, nullable=True)
    ell_french_2 = Column(Float, nullable=True)
    ell_russian_1 = Column(Integer, nullable=True)
    ell_russian_2 = Column(Float, nullable=True)
    ell_korean_1 = Column(Integer, nullable=True)
    ell_korean_2 = Column(Float, nullable=True)
    ell_urdu_1 = Column(Integer, nullable=True)
    ell_urdu_2 = Column(Float, nullable=True)
    ell_other_1 = Column(Integer, nullable=True)
    ell_other_2 = Column(Float, nullable=True)
    ela_test_takers = Column(Integer, nullable=True)
    ela_level_1_1 = Column(Integer, nullable=True)
    ela_level_1_2 = Column(Float, nullable=True)
    ela_level_2_1 = Column(Integer, nullable=True)
    ela_level_2_2 = Column(Float, nullable=True)
    ela_level_3_1 = Column(Integer, nullable=True)
    ela_level_3_2 = Column(Float, nullable=True)
    ela_level_4_1 = Column(Integer, nullable=True)
    ela_level_4_2 = Column(Float, nullable=True)
    ela_l3_l4_1 = Column(Integer, nullable=True)
    ela_l3_l4_2 = Column(Float, nullable=True)
    math_test_takers = Column(Integer, nullable=True)
    math_level_1_1 = Column(Integer, nullable=True)
    math_level_1_2 = Column(Float, nullable=True)
    math_level_2_1 = Column(Integer, nullable=True)
    math_level_2_2 = Column(Float, nullable=True)
    math_level_3_1 = Column(Integer, nullable=True)
    math_level_3_2 = Column(Float, nullable=True)
    math_level_4_1 = Column(Integer, nullable=True)
    math_level_4_2 = Column(Float, nullable=True)
    math_l3_l4_1 = Column(Integer, nullable=True)
    math_l3_l4_2 = Column(Float, nullable=True)


class Chart(Base):
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    file = Column(String, nullable=True)
